---

language: python

python:
  - 2.7

install:
  - pip install ansible

script:
  - sudo apt-get install -y apache2
  - git clone https://github.com/geerlingguy/ansible-role-git ../geerlingguy.git
  - git clone https://github.com/geerlingguy/ansible-role-php ../geerlingguy.php
  - git clone https://github.com/geerlingguy/ansible-role-composer ../geerlingguy.composer
  - git clone https://github.com/fubarhouse/fubarhouse.dvm ../fubarhouse.dvm
  - cd tests
  - ansible-playbook -i inventory playbook.yml --syntax-check
  - ansible-playbook -i inventory playbook.yml --sudo -vvvv
