---

language: go
go:
  - 1.8.x
services: docker

env:
  - distro: ubuntu1604
    init: /sbin/init
    run_opts: "--privileged"
    playbook: test.yml
  - distro: ubuntu1404
    init: /sbin/init
    run_opts: "--privileged"
    playbook: test.yml
  - distro: ubuntu1204
    init: /sbin/init
    run_opts: "--privileged"
    playbook: test.yml
  - distro: centos6
    init: "/sbin/init"
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    playbook: test.yml
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    playbook: test.yml
  - distro: debian8
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    playbook: test.yml
  # - distro: fedora24
  #   init: /usr/lib/systemd/systemd
  #   run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  #   playbook: test.yml

before_install:

  # Pull our container.
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

  # Ensure composer has installed drush.
  - 'composer require drush/drush'

  # Find drush.
  - 'which drush'

script:

  - container_id=$(mktemp)

  # Run golang tests
  - go test -v ./...

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/