---

language: python

python:
  - 2.7

install:
  - pip install ansible

script:
  - cd tests
  - ansible-galaxy install -r requirements.yml
  - ansible-playbook -i inventory playbook.yml --syntax-check
  - ansible-playbook -i inventory playbook.yml --sudo -vvvv
