#!/bin/bash

function DVM () {

  function _NOARG () {
    if [[ -z "${CLEANARG}" ]]; then
      echo "  Missing argument <version>";
      exit 0;
    fi
  }

  function _INITIALIZE () {
    function __GETCOMPOSER () {
      if [[ -z $(which composer) ]]; then
        echo "Installing composer";
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer
      fi
    }
    function __UNZIP () {
      if [[ -z $(which unzip) ]]; then
        echo "Installing unzip";
        sudo apt-get install unzip
      fi
    }
    __GETCOMPOSER;
  }

  function _PRERUN () {
    if [[ ! -e "${DRUSHDIR}/drush" ]] && [[ ! -d "${DRUSHDIR}" ]]; then
      mkdir -p "${DRUSHDIR}" && cd "${DRUSHDIR}";
      curl -sS https://getcomposer.org/installer | php;
      php composer.phar require drush/drush;
    fi
  }

function _RUN () {

    case "${*}" in
      *"use"*)        _SWITCH; ;;
      *"exec"*)       _EXEC ;;
      *"current"*)    drush --version | cut -d: -f2; ;;
      *"status"*)     drush status; ;;
      *"install"*)    _INSTALL; ;;
      *"ls-local"*)   _FETCH_LOCAL; ;;
      *"ls-remote"*)  _FETCH_REMOTE; ;;
      *"initialize"*) _INITIALIZE; ;;
    esac
  }

  function _SWITCH () {
    if [[ -n "${CLEANARG}" ]]; then
      if [[ -e "${DRUSHVERDIR}/vendor/bin/drush" ]]; then
        echo "  Changing to v${CLEANARG}";
        echo "  Password may be required..."
        sudo rm -f "/usr/local/bin/drush";
        sudo ln -s "${DRUSHVERDIR}/vendor/bin/drush" "/usr/local/bin/drush";
        INSTALLED=$(drush --version | cut -d: -f2);
        INSTALLED=${INSTALLED/  /};
        INSTALLED=${INSTALLED/ /};
        echo "  Drush is now using ${INSTALLED}";
      else
        echo "  Drush v${CLEANARG} is not installed."
      fi
    else
      _NOARG;
    fi
    exit 0;
  }

  function _EXEC () {
    CLEANARG=$(echo "${CLEANARG}" | cut -d\  -f1);
    DRUSHVERDIR="${DRUSHDIR}/versions/drush-${CLEANARG}";
    if [[ -n "${CLEANARG}" ]]; then
      if [[ -e "${DRUSHVERDIR}/vendor/bin/drush" ]]; then
        COMMAND="${ARGUMENTS[*]}";
        COMMAND=${COMMAND/exec/};
        COMMAND=${COMMAND/${CLEANARG}/};
        COMMAND=${COMMAND/  / };
        echo "${DRUSHVERDIR}/vendor/bin/drush ${COMMAND}";
        eval "${DRUSHVERDIR}/vendor/bin/drush ${COMMAND}";
      else
        echo "  Drush v${CLEANARG} is not installed."
      fi
    else
      _NOARG;
    fi
    exit 0;
  }

  function _INSTALL () {
    function __GETVERSIONS () {
      echo "  Checking version number...";
      if [[ -n "${CLEANARG}" ]]; then
        if [[ -n $(cd "${DRUSHDIR}" && composer show drush/drush | grep versions | grep "${CLEANARG}") ]]; then
          VALIDVERSION=true;
          echo "  Version ${CLEANARG} was found.";
        else
          VALIDVERSION=false;
          echo "  Version ${CLEANARG} was not found.";
        fi
      fi
    }
    function __INSTALL_ACTION () {
      echo "||||||";
      if [[ "${BASEVERSION}" == "5" ]]; then
        mkdir -p "${DRUSHDIR}/versions/${X}";
        cd "${DRUSHDIR}/versions/";
        wget "https://github.com/drush-ops/drush/archive/${CLEANARG}.zip"
        unzip "${CLEANARG}.zip"
        rm -f "${CLEANARG}.zip";
        sudo mv -f "./drush-${CLEANARG}" ./drush5
        if [[ -d "${CLEANARG}" ]]; then
          rm -rf "${CLEANARG}";
        fi
      fi
      if [[ "${BASEVERSION}" == "6" ]] || [[ "${BASEVERSION}" == "7" ]] || [[ "${BASEVERSION}" == "8" ]]; then
        mkdir -p "${DRUSHVERDIR}";
        cd "${DRUSHVERDIR}";
        curl -sS https://getcomposer.org/installer | php;
        php composer.phar require "drush/drush:${VERSION}";
      fi
    }
    function __INSTALL () {
      if [[ -n "${CLEANARG}" ]]; then
        if [[ -d "${DRUSHVERDIR}" ]]; then
          echo "Drush v${CLEANARG} has already been installed.";
        else
          __GETVERSIONS;
          __INSTALL_ACTION;
        fi
      else
        _NOARG;
      fi
    }
    function __REINSTALL () {
      if [[ -n "${CLEANARG}" ]]; then
        if [[ ! -d "${DRUSHVERDIR}" ]]; then
          __GETVERSIONS;
          __INSTALL_ACTION;
        else
          echo "Drush v${CLEANARG} has already been installed.";
          exit 0;
        fi
      else
        _NOARG;
      fi
    }
    function __UNINSTALL () {
      if [[ -n "${CLEANARG}" ]]; then
        INSTALLED=$(drush --version | cut -d: -f2);
        INSTALLED=${INSTALLED/  /};
        INSTALLED=${INSTALLED/ /};
        TOUNINSTALL=$(_FETCH_LOCAL);
        TOUNINSTALL=${TOUNINSTALL/  /};
        TOUNINSTALL=${TOUNINSTALL/ /};
        if [[ ! "${TOUNINSTALL}" == *"${INSTALLED}"* ]]; then
          rm -rf "${DRUSHDIR}/versions/drush-${CLEANARG}";
          echo "Drush v${CLEANARG} has been uninstalled.";
        else
          echo "You cannot uninstall a currently active version."
          exit 0;
        fi
      else
        _NOARG;
      fi
    }
    case "${STATE}" in
      "install" )   __INSTALL; ;;
      "reinstall" ) __REINSTALL; ;;
      "uninstall" ) __UNINSTALL; ;;
    esac
  }

  function _FETCH_REMOTE () {
    function _GETVERSIONS () {
      echo "  Checking version number...";
      if [[ -n "${CLEANARG}" ]]; then
        if [[ -n $(cd "${DRUSHDIR}" && composer show drush/drush | grep versions | grep "${CLEANARG}") ]]; then
          VALIDVERSION=true;
          echo "  Version ${CLEANARG} was found.";
        else
          VALIDVERSION=false;
          echo "  Version ${CLEANARG} was not found.";
        fi
      fi
    }
    _GETVERSIONS;
    declare -a AVAILABLEVERSIONS=($(composer show drush/drush | grep versions | tr ", " "\n"));
    if [[ -z "${CLEANARG}" ]]; then
      for X in "${AVAILABLEVERSIONS[@]}"; do echo "      ${X}" | grep "6."; done
      for X in "${AVAILABLEVERSIONS[@]}"; do echo "      ${X}" | grep "7."; done
      for X in "${AVAILABLEVERSIONS[@]}"; do echo "      ${X}" | grep "8."; done
    else
      for X in "${AVAILABLEVERSIONS[@]}"; do echo "      ${X}" | grep "${CLEANARG}"; done
    fi
    exit 0;
  }

  function _FETCH_LOCAL () {
    INSTALLED=$(drush --version | cut -d: -f2);
    INSTALLED=${INSTALLED/  /};
    INSTALLED=${INSTALLED/ /};
    for X in "${VERSIONSINSTALLED[@]}"; do
      if [[ "${X}" == "drush-${INSTALLED}" ]]; then tput setaf 2; fi
      if [[ "${X}" = *"drush-${BASEVERSION}"* ]]; then
        if [[ -z "${CLEANARG}" ]]; then
          echo "      ${X}";
        else
          echo "      ${X}" | grep ${CLEANARG};
        fi
      fi
      if [[ "${X}" == "drush-${INSTALLED}" ]]; then tput sgr0; fi
    done
    exit 0;
  }

  function _HELP () {
    echo " Drush Version Manager";
    echo " ";
    echo " Note: <version> refers to any version-like string dvm understands. This includes:";
    echo "   - full version numbers (7.0.0, 7.1.0, 8.0.0-rc3)";
    echo " ";
    echo " Usage:";
    echo "   dvm help                                  Show this message.";
    echo "   dvm install <version>                     Download and install <version>.";
    echo "   dvm reinstall <version>                   Reinstall a version.";
    echo "   dvm uninstall <version>                   Uninstall a version.";
    echo "   dvm use <version>                         Change the drush symlink to use another version.";
    echo "   dvm exec <version> <command>              Change the drush symlink to use another version.";
    echo "   dvm current                               Display currently activated version.";
    echo "   dvm status                                Display current status.";
    echo "   dvm ls-local                              List installed versions.";
    echo "   dvm ls-local <version>                    List installed versions matching a search criteria";
    echo "   dvm ls-remote                             List remote versions available for install";
    echo "   dvm ls-remote <version>                   List remote versions matching a search criteria";
    echo " ";
    echo " Example:";
    echo "   dvm install 7.0.0                         Install a specific version number";
    echo "   dvm use 7.0.0                             Tells the system to use drush 7.0.0";
    echo "   dvm exec 7.0.0 status                     Use Drush 7.0.0 to execute the status command3";
  }

  if [[ "${*}" == *"help"* ]] || [[ -z "${*}" ]]; then
    _HELP;
    exit 0;
  fi

  ARGUMENTS="${*}";
  _PRERUN "${*}";
  _RUN "${ARGUMENTS}";
}

function SETVARS () {

  if [[ "${*}" == *"reinstall"* ]]; then STATE="reinstall"; fi
  if [[ "${*}" == *"uninstall"* ]]; then STATE="uninstall"; fi
  if [[ "${*}" == *"install"* ]] && [[ "${STATE}" != "reinstall" ]] && [[ "${STATE}" != "uninstall" ]]; then STATE="install"; fi
  if [[ "${*}" == *"exec"* ]]; then STATE="exec"; fi

  CLEANARG="${*}";
  CLEANARG=${CLEANARG/uninstall/};
  CLEANARG=${CLEANARG/reinstall/};
  CLEANARG=${CLEANARG/install/};
  CLEANARG=${CLEANARG/update/};
  CLEANARG=${CLEANARG/use/};
  CLEANARG=${CLEANARG/exec/};
  CLEANARG=${CLEANARG/ls-local/};
  CLEANARG=${CLEANARG/ls-remote/};
  CLEANARG=${CLEANARG/  /};
  CLEANARG=${CLEANARG/ /};

  case "${CLEANARG}" in
    5*)  VERSION="${CLEANARG}"; ;;
    6*)  VERSION="${CLEANARG}"; ;;
    7*)  VERSION="${CLEANARG}"; ;;
    8*)  VERSION="${CLEANARG}"; ;;
  esac

  DRUSHDIR="${HOME}/drush";
  BASEVERSION=${VERSION::1};
  DRUSHVERDIR="${DRUSHDIR}/versions/drush-${VERSION}";

  declare -a VERSIONSINSTALLED=();
  for ITEM in $(find "${DRUSHDIR}/versions" -maxdepth 1 -type d | cut -d/ -f6 | grep "drush-" | grep -v "master"); do
    VERSIONSINSTALLED+=("${ITEM}");
  done

}

SETVARS "${*}";
DVM "${*}";
